[package]
name = "kernel"
version = "0.1.0"
edition.workspace = true

[lib]
name = "os"
path = "src/lib.rs"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
common = {path = "../common"}
riscv = "0.11.1"
